name: Deploy to test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploying:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: node213-eu.n0c.com
          username: vrtvjmeg
          password: "#SG&(3#NL(aa5JN&z&"
          port: 5022
          script: echo "ça marche"